service: book-ind

frameworkVersion: "3"
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action: ["dynamodb:Scan", "dynamodb:PutItem"]
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/users

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - httpApi:
          path: /
          method: get
    environment:
      users_api: https://5c11c8bnbg.execute-api.us-east-1.amazonaws.com/users
      book_api: https://5c11c8bnbg.execute-api.us-east-1.amazonaws.com/book

  get-users:
    handler: functions/get-users.handler
    events:
      - httpApi:
          path: /users
          method: get
    environment:
      users_table: users

  post-booking:
    handler: functions/post-booking.handler
    events:
      - httpApi:
          path: /book
          method: post
    environment:
      users_table: users

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
